/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  GAModel,
} from './ga-utils/GAModel';


export namespace Components {
  interface GaForm {
    'model': GAModel;
    'side': String;
  }
  interface GaList {
    'model': GAModel;
    'side': String;
  }
  interface GraphqlAdmin {
    'dataPath': string;
    'dataSource': string;
  }
}

declare namespace LocalJSX {
  interface GaForm extends JSXBase.HTMLAttributes {
    'model'?: GAModel;
    'onFormSubmittedEvent'?: (event: CustomEvent<any>) => void;
    'onModelUpdated'?: (event: CustomEvent<any>) => void;
    'onSubTableSelected'?: (event: CustomEvent<any>) => void;
    'side'?: String;
  }
  interface GaList extends JSXBase.HTMLAttributes {
    'model'?: GAModel;
    'onLeftRowSelected'?: (event: CustomEvent<any>) => void;
    'onRightRowSelected'?: (event: CustomEvent<any>) => void;
    'side'?: String;
  }
  interface GraphqlAdmin extends JSXBase.HTMLAttributes {
    'dataPath'?: string;
    'dataSource'?: string;
  }

  interface IntrinsicElements {
    'ga-form': GaForm;
    'ga-list': GaList;
    'graphql-admin': GraphqlAdmin;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLGaFormElement extends Components.GaForm, HTMLStencilElement {}
  var HTMLGaFormElement: {
    prototype: HTMLGaFormElement;
    new (): HTMLGaFormElement;
  };

  interface HTMLGaListElement extends Components.GaList, HTMLStencilElement {}
  var HTMLGaListElement: {
    prototype: HTMLGaListElement;
    new (): HTMLGaListElement;
  };

  interface HTMLGraphqlAdminElement extends Components.GraphqlAdmin, HTMLStencilElement {}
  var HTMLGraphqlAdminElement: {
    prototype: HTMLGraphqlAdminElement;
    new (): HTMLGraphqlAdminElement;
  };

  interface HTMLElementTagNameMap {
    'ga-form': HTMLGaFormElement;
    'ga-list': HTMLGaListElement;
    'graphql-admin': HTMLGraphqlAdminElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

